#ifndef THREAD_DEFINES_H
#define THREAD_DEFINES_H

#define THREAD_DEBUG_MODE

#define HIGH_PRIORITY_VALUE 30

#define MEDIUM_PRIORITY_VALUE 20;

#define UPDATE_DISPLAY_PRIORITY_VALUE 10;

#define LORA_PRIORITY_VALUE 5;

#endif // THREAD_DEFINES_H
